// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiPLI1lkWfPfpbvVXJ08Tfrtp88e4xvIA',
    appId: '1:746895338475:web:b2f4f75d8f55370d2307ae',
    messagingSenderId: '746895338475',
    projectId: 'unifood-31',
    authDomain: 'unifood-31.firebaseapp.com',
    storageBucket: 'unifood-31.appspot.com',
    measurementId: 'G-1NJRZMNFY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcPvwlnEM5j95fYRBUvN26bqFR6pQqJc',
    appId: '1:746895338475:android:3afb4f328f90e0c02307ae',
    messagingSenderId: '746895338475',
    projectId: 'unifood-31',
    storageBucket: 'unifood-31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCAUnXV8Zj1TyBT0-VLdtXQNt-oYpwqoc',
    appId: '1:746895338475:ios:d211763be0c933002307ae',
    messagingSenderId: '746895338475',
    projectId: 'unifood-31',
    storageBucket: 'unifood-31.appspot.com',
    iosBundleId: 'com.example.unifood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCAUnXV8Zj1TyBT0-VLdtXQNt-oYpwqoc',
    appId: '1:746895338475:ios:deb9bd1231ac069e2307ae',
    messagingSenderId: '746895338475',
    projectId: 'unifood-31',
    storageBucket: 'unifood-31.appspot.com',
    iosBundleId: 'com.example.unifood.RunnerTests',
  );
}
